DROP SCHEMA IF EXISTS A1;
CREATE SCHEMA A1;
USE A1;
SET SQL_SAFE_UPDATES = 0;
DROP TABLE IF EXISTS roles;
CREATE TABLE roles(
id_rol INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
rol ENUM("Estudiante","Docente") NOT NULL
);
INSERT INTO roles(rol) VALUES ("Docente");
INSERT INTO roles(rol) VALUES ("Estudiante");
SELECT * FROM roles;